name: rupp_final_mad
description: Final project MAD II year4 s1
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  intl: ^0.19.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
